export const HERO_SLIDES = [
  {
    id: "ready-to-wear",
    title: "Effortless Ready-to-Wear",
    subtitle: "Timeless pieces crafted for modern elegance.",
    description: "Discover our curated collection of everyday luxury",
    cta: "Shop Ready-to-Wear",
    href: "/ready-to-wear",
    img: "/home/1.jpg",
    alt: "Model wearing tailored coat in elegant ready-to-wear collection",
    badge: "New Collection",
  },
  {
    id: "beauty-hair",
    title: "Beauty & Hair Edit",
    subtitle: "Where self-care meets sophistication.",
    description: "Premium skincare and haircare essentials",
    cta: "Explore Beauty",
    href: "/beauty-hair",
    img: "/home/2.jpg",
    alt: "Luxurious skincare and beauty products in studio lighting",
    badge: "Best Sellers",
  },
  {
    id: "jewelry",
    title: "Jewelry & Accessories",
    subtitle: "Adorn yourself with effortless charm.",
    description: "Heirloom-quality pieces that last",
    cta: "Shop Jewelry",
    href: "/jewelry",
    img: "/home/3.jpg",
    alt: "Closeup of elegant gold jewelry on neutral background",
    badge: "Trending",
  },
];

export const HERO_CAMPAIGN = {
  active: true,
  label: "LIMITED: Bridal Capsule — 48 HRS",
  href: "/ready-to-wear/bridal-shower",
};
export const bentoItems = [
  {
    id: 1,
    title: "Ready to Wear",
    subtitle: "Curated Collections",
    description: "Timeless pieces for men, women & kids",
    img: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1400&q=80",
    span: "md:col-span-2 md:row-span-2",
    accent: "gold",
    link: "/ready-to-wear",
  },
  {
    id: 2,
    title: "Bridal Shower",
    subtitle: "Wedding Elegance",
    description: "Gowns for your special day",
    img: "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80",
    span: "md:col-span-1 md:row-span-1",
    accent: "brand",
    link: "/ready-to-wear/bridal-shower",
  },
  {
    id: 3,
    title: "Beauty & Hair",
    subtitle: "Self Care Essentials",
    description: "Premium skincare & haircare",
    img: "https://images.unsplash.com/photo-1596704017254-9b121068ec31?auto=format&fit=crop&w=800&q=80",
    span: "md:col-span-1 md:row-span-1",
    accent: "sand",
    link: "/beauty-hair",
  },
  {
    id: 4,
    title: "Accessories",
    subtitle: "The Finishing Touch",
    description: "Bags, scarves & statement pieces",
    img: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=1200&q=80",
    span: "md:col-span-2 md:row-span-1",
    accent: "taupe",
    link: "/accessories",
  },
  {
    id: 5,
    title: "Jewelry",
    subtitle: "Timeless Adornments",
    description: "Heirloom-quality pieces",
    img: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=1200&q=80",
    span: "md:col-span-1 md:row-span-1",
    accent: "gold",
    link: "/jewelry",
  },
  {
    id: 6,
    title: "Cosmetics",
    subtitle: "Beauty Essentials",
    description: "Luxury makeup & fragrances",
    img: "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=1200&q=80",
    span: "md:col-span-1 md:row-span-1",
    accent: "sand",
    link: "/cosmetics",
  },
  {
    id: 7,
    title: "Kids Fashion",
    subtitle: "Little Ones",
    description: "Stylish pieces for children",
    img: "https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?auto=format&fit=crop&w=1200&q=80",
    span: "md:col-span-1 md:row-span-1",
    accent: "taupe",
    link: "/ready-to-wear/kids",
  },
  {
    id: 8,
    title: "Sale",
    subtitle: "Limited Time",
    description: "Up to 50% off selected items",
    img: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1200&q=80",
    span: "md:col-span-1 md:row-span-1",
    accent: "gold",
    link: "/sale",
    badge: "Hot",
  },
];

export const categories = [
  {
    name: "Ready to Wear",
    slug: "ready-to-wear",
    subcategories: [
      { name: "Men", slug: "men" },
      { name: "Women", slug: "women" },
      { name: "Kids", slug: "kids" },
      { name: "Bridal Shower", slug: "bridal-shower" },
    ],
  },
  {
    name: "Beauty & Hair",
    slug: "beauty-hair",
  },
  {
    name: "Accessories",
    slug: "accessories",
  },
  {
    name: "Jewelry",
    slug: "jewelry",
  },
  {
    name: "Cosmetics",
    slug: "cosmetics",
  },
  {
    name: "Sale",
    slug: "sale",
  },
];

export const featuredProducts = [
  {
    id: 1,
    title: "Tailored Trench",
    category: "Ready to Wear",
    price: "₦85,000",
    img: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=900&q=80",
    badge: "New",
  },
  {
    id: 2,
    title: "Silk Evening Dress",
    category: "Bridal Shower",
    price: "₦42,000",
    img: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 3,
    title: "Gold Hoop Earrings",
    category: "Jewelry",
    price: "₦18,500",
    img: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 4,
    title: "Luxury Face Serum",
    category: "Beauty & Hair",
    price: "₦25,000",
    img: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=900&q=80",
    badge: "Bestseller",
  },
];
