// lib/constants/mockProducts.js
export const products = [
  {
    id: "p1",
    name: "Tailored Trench Coat",
    slug: "tailored-trench-coat",
    category: "ready-to-wear",
    subcategory: "women",
    price: 85000,
    currency: "NGN",
    color: "Mocha",
    size: ["XS", "S", "M", "L"],
    material: "Wool-blend",
    tags: ["new", "outerwear", "best-seller"],
    image:
      "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "p2",
    name: "Linen Button Shirt",
    slug: "linen-button-shirt",
    category: "ready-to-wear",
    subcategory: "men",
    price: 42000,
    currency: "NGN",
    color: "Beige",
    size: ["S", "M", "L", "XL"],
    material: "Linen",
    tags: ["essentials"],
    image:
      "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "p3",
    name: "Silk Slip Dress",
    slug: "silk-slip-dress",
    category: "ready-to-wear",
    subcategory: "women",
    price: 42000,
    currency: "NGN",
    color: "Dusty Rose",
    size: ["XS", "S", "M"],
    material: "Silk",
    tags: ["evening", "luxury"],
    image:
      "https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "p4",
    name: "Gold Hoop Earrings",
    slug: "gold-hoop-earrings",
    category: "jewelry",
    price: 18500,
    currency: "NGN",
    color: "Gold",
    size: [],
    material: "Gold-plated",
    tags: ["accessory", "gift"],
    image:
      "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "p5",
    name: "Hydrating Facial Serum",
    slug: "hydrating-facial-serum",
    category: "beauty-hair",
    price: 25000,
    currency: "NGN",
    color: "Clear",
    size: [],
    material: "Serum",
    tags: ["skincare"],
    image:
      "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "p6",
    name: "Classic Leather Belt",
    slug: "classic-leather-belt",
    category: "accessories",
    price: 15000,
    currency: "NGN",
    color: "Brown",
    size: ["M", "L"],
    material: "Leather",
    tags: ["essentials"],
    image:
      "https://images.unsplash.com/photo-1624222247344-550fb60583c2?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "p7",
    name: "Kids Playful Tee",
    slug: "kids-playful-tee",
    category: "ready-to-wear",
    subcategory: "kids",
    price: 9000,
    currency: "NGN",
    color: "Mint",
    size: ["2-3Y", "4-5Y"],
    material: "Cotton",
    tags: ["kids"],
    image:
      "https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "p8",
    name: "Bridal Lace Gown",
    slug: "bridal-lace-gown",
    category: "ready-to-wear",
    subcategory: "bridal-shower",
    price: 450000,
    currency: "NGN",
    color: "Ivory",
    size: ["S", "M", "L"],
    material: "Lace",
    tags: ["bridal", "exclusive"],
    image:
      "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "p9",
    name: "Nude Matte Lipstick",
    slug: "nude-matte-lipstick",
    category: "cosmetics",
    price: 6500,
    currency: "NGN",
    color: "Nude",
    size: [],
    material: "Makeup",
    tags: ["beauty"],
    image:
      "https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "p10",
    name: "Statement Sunglasses",
    slug: "statement-sunglasses",
    category: "accessories",
    price: 32000,
    currency: "NGN",
    color: "Black",
    size: [],
    material: "Acetate",
    tags: ["sunglasses", "summer"],
    image:
      "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "p11",
    name: "Velvet Clutch",
    slug: "velvet-clutch",
    category: "accessories",
    price: 28000,
    currency: "NGN",
    color: "Emerald",
    size: [],
    material: "Velvet",
    tags: ["evening", "luxury"],
    image:
      "https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "p12",
    name: "Limited Edition Perfume",
    slug: "limited-edition-perfume",
    category: "beauty-hair",
    price: 105000,
    currency: "NGN",
    color: "Amber",
    size: [],
    material: "Fragrance",
    tags: ["limited", "scent"],
    image:
      "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=1200&q=80",
  },
];
